import pandas as pd
import numpy as np
import csv
from glob import glob
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime

lista_dfs = []
files = glob(r'Arquivos\indicadores-continuidade-coletivos-*.csv')
def preprocessamento():
    for file in files:
        df = pd.read_csv(file, sep=';', encoding='iso-8859-1')
        for column in df.columns:
            column_new = column.strip()
            df[column] = df[column_new]
        df = df[df['SigAgente'].str.strip()=='ELETROPAULO']
        df['VlrIndiceEnviado'] = df['VlrIndiceEnviado'].str.replace(',','.').astype('float')
        df['Data'] = pd.to_datetime(
        df['AnoIndice'].astype(str) + '-' + 
        df['NumPeriodoIndice'].astype(str) + '-01')
        df['DscConjUndConsumidoras'] = df['DscConjUndConsumidoras'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8').str.upper()
        df['Regiao'] = df['DscConjUndConsumidoras']
        conjuntos = {
            'AEROPORTO': 'ZS',
            'AGUA BRANCA': 'ZO',
            'ALEX. DE GUSMAO': 'RM SE',
            'ALPHAVILLE': 'RM NO',
            'ALTO DA BOA VISTA': 'ZS',
            'ALVARENGA': 'RM SE',
            'AMERICANOPOLIS': 'ZS',
            'ANASTACIO': 'ZO',
            'ANCHIETA': 'RM SE',
            'ANHEMBI': 'ZN',
            'ARICANDUVA': 'ZL',
            'AUGUSTA': 'ZC',
            'AUTONOMISTAS': 'RM ZO',
            'BANDEIRANTES': 'ZS',
            'BANDEIRANTES_RETICULADO': 'ZS',
            'BARRA FUNDA': 'ZO',
            'BARTIRA': 'EXTREMO LESTE',
            'BARUERI': 'RM ZO',
            'BATISTINI': 'RM SE',
            'BAVIERA': 'RM SE',
            'BELA ALIANCA': 'ZO',
            'BRAS': 'ZC',
            'BRASILANDIA': 'ZN',
            'BRIGADEIRO': 'ZCS',
            'BUENOS AIRES': 'ZC',
            'BUTANTA': 'ZO',
            'CAMBUCI': 'ZC',
            'CAMPESTRE': 'RM SE',
            'CAMPO LIMPO': 'SO',
            'CANAA': 'ZS',
            'CANINDE': 'ZC',
            'CAPAO REDONDO': 'EXTREMO SUL',
            'CAPELA': 'ZS',
            'CAPUAVA': 'RM SE',
            'CARAPICUIBA': 'RM ZO',
            'CARRAO': 'ZL',
            'CASA VERDE': 'ZN',
            'CASTELO': 'ZC',
            'CATUMBI': 'ZL',
            'CAUCAIA': 'RM ZO',
            'CENTRO': 'ZC',
            'CENTRO JARDINS': 'ZC',
            'CLEMENTINO': 'ZCS',
            'CLAUDIA': 'RM SE',
            'COIMBRA': 'RM SE',
            'COMANDANTE TAYLOR': 'ZS',
            'CONGONHAS': 'ZS',
            'CONTINENTAL': 'ZO',
            'COTIA': 'RM ZO',
            'CUPECE': 'ZS',
            'CURSINO': 'ZCS',
            'DIADEMA': 'RM SE',
            'ECO PERUS': 'ZO',
            'EMBU': 'RM SO',
            'EMBU GUACU': 'RM SO',
            'ERMELINO MATARAZZO': 'EXTREMO LESTE',
            'ESPLANADA': 'RM ZO',
            'GATO PRETO': 'RM NO',
            'GERMANIA': 'SO',
            'GOMES CARDIM': 'ZL',
            'GOPOUVA': 'RM NE',
            'GRANJA JULIETA': 'ZS',
            'GRANJA VIANA': 'RM ZO',
            'GUAIANAZES': 'EXTREMO LESTE',
            'GUARAPIRANGA': 'EXTREMO SUL',
            'GUMERCINDO': 'ZCS',
            'HIPODROMO': 'ZL',
            'IBIRAPUERA': 'ZCS',
            'IMIGRANTES': 'ZS',
            'INTERLAGOS': 'ZS',
            'IPIRANGA': 'ZS',
            'ITAIM': 'ZCS',
            'ITAIM PAULISTA': 'EXTREMO LESTE',
            'ITAPECERICA DA SERRA': 'RM SO',
            'ITAPECERICA DA SERRA - CENTRO': 'RM SO',
            'ITAPEVI': 'RM ZO',
            'ITAQUERA': 'ZL',
            'ITAQUERA - IGUATEMI': 'ZL',
            'ITAQUERUNA': 'ZS',
            'JABAQUARA': 'ZS',
            'JACANA': 'ZN',
            'JAGUARE': 'ZO',
            'JANDIRA': 'RM ZO',
            'JARAGUA': 'EXTREMO NORTE',
            'JARDIM SAO LUIS': 'ZS',
            'JD. DA GLORIA': 'ZCS',
            'JOAO CLIMACO': 'ZS',
            'JORDANESIA': 'RM NO',
            'JUQUITIBA': 'RM SO',
            'JUSCELINO KUBITSCHEK': 'ZCS',
            'LAPA': 'ZO',
            'LEOPOLDINA': 'ZO',
            'LIMAO': 'ZN',
            'LUBECA': 'ZS',
            'MANDAQUI': 'ZN',
            'MATEUS': 'ZL',
            'MAUA': 'RM SE',
            'MENINOS': 'RM SE',
            'MIGUEL PAULISTA': 'ZL',
            'MIGUEL REALE': 'ZO',
            'MIGUEL REALE_RETICULADO': 'ZC',
            'MONCOES': 'ZCS',
            'MONTE AZUL': 'EXTREMO SUL',
            'MONTE BELO': 'RM ZO',
            'MONTE SANTO': 'ZL',
            'MONUMENTO': 'ZS',
            'MOOCA': 'ZCL',
            'MORUMBI': 'ZO',
            'NACOES': 'RM SE',
            'NOVO BANDEIRANTES': 'DUVIDA',
            'NOVO MUNDO': 'ZN',
            'OESTE': 'ZO',
            'ORATORIO': 'ZL',
            'OSASCO': 'RM ZO',
            'PAINEIRAS': 'RM SO',
            'PARELHEIROS': 'EXTREMO SUL',
            'PARNAIBA': 'RM NO',
            'PARQUE DOS LAGOS': 'ZS',
            'PARQUE SAO DOMINGOS': 'ZO',
            'PAULA SOUZA': 'ZC',
            'PENHA': 'ZL',
            'PENHA NOVA': 'ZL',
            'PERI': 'ZN',
            'PINHEIROS': 'ZO',
            'PIRAPORINHA': 'RM SE',
            'PIRITUBA': 'ZO',
            'PLANALTO': 'ZS',
            'PLANALTO PAULISTA': 'ZCS',
            'PONTA PORA': 'ZO',
            'PONTE PRETA': 'RM SE',
            'RAPOSO TAVARES': 'ZO',
            'REMEDIOS': 'ZO',
            'REPRESINHA': 'RM ZO',
            'RIBEIRAO PIRES': 'RM SE',
            'RIBEIRAO PIRES-RIO G. DA SERRA': 'RM SE',
            'RIO BONITO': 'EXTREMO SUL',
            'RIO GRANDE': 'RM SE',
            'ROSELANDIA': 'RM ZO',
            'SABARA': 'ZS',
            'SACOMA': 'ZS',
            'SANTA MARIA': 'RM ZO',
            'SANTANA': 'ZN',
            'SANTO AMARO': 'ZS',
            'SANTO ANDRE': 'RM SE',
            'SANTO ANDRE - REPRESA': 'RM SE',
            'SAO BERNARDO DO CAMPO': 'RM SE',
            'SAO BERNARDO DO CAMPO -REPRESA': 'RM ZS',
            'SAO CAETANO DO SUL': 'RM SE',
            'SAO MATEUS': 'EXTREMO LESTE',
            'SAO MIGUEL PAULISTA': 'EXTREMO LESTE',
            'SAO PAULO  CENTRO': 'ZC',
            'SAO PAULO REPRESA SUL': 'ZS',
            'SAPOPEMBA': 'ZL',
            'SAUDE': 'ZS',
            'SERTAOZINHO': 'RM SE',
            'SILVESTRE': 'RM SE',
            'SUMARE': 'ZO',
            'TABOAO DA SERRA': 'RM SO',
            'TAIPAS': 'EXTREMO NORTE',
            'TAMBORE': 'RM NO',
            'TAMOIO': 'RM SE',
            'TATUAPE': 'ZL',
            'TENENTE MARQUES': 'RM NO',
            'TIRADENTES': 'EXTREMO LESTE',
            'TOMAZ EDSON': 'ZO',
            'TUCURUVI': 'ZN',
            'TUIUTI': 'ZL',
            'UTINGA': 'RM SE',
            'VARGEM GRANDE': 'RM SO',
            'VARGINHA': 'EXTREMO SUL',
            'VILA ALMEIDA': 'RM ZO',
            'VILA EMA': 'ZL',
            'VILA FORMOSA': 'ZL',
            'VILA GUILHERME': 'ZL',
            'VILA MARIANA': 'ZS',
            'VILA MATILDE': 'ZL',
            'VILA MEDEIROS': 'ZN',
            'VILA PAULA': 'RM SE',
            'VILA PAULICEIA': 'RM SE',
            'VILA PROSPERIDADE': 'RM SE',
            'VILA PRUDENTE': 'ZL',
            'VILA TALARICO': 'ZL',
            'VITORIA': 'RM SE'
        }

        df['Regiao'] = df['Regiao'].map(conjuntos)
        df['Distribuidora'] = np.where(df['Data']>'2018-05-01', 'ENEL', 'Eletropaulo')
        

    return df